### PR TITLE
Capitalize `JavaScript` correctly

### PR DESCRIPTION
**Pull request by arthurvr**
This kind of super-small improvements make awesome lists even more awesome :wink:

### CODE REVIEW

**Comment by hueitan** [comment]
Thanks @arthurvr 
I have a question about that,
`Javascript` `JavaScript` `javascript` What's the difference between them

**Comment by hueitan** [comment]
BTW, Move to https://github.com/aloisdg/awesome-regex

**Comment by arthurvr** [comment]
`JavaScript` is just the name. The only difference is the capitalisation. It's just good to do it correct. Just like I wouldn't write your name as HuEi :wink:

**Comment by hueitan** [comment]
Ok! Thanks for your comment :smile:

**Pull request closed without merging**
